import type { WorkflowTemplate } from '@/lib/workflows/types';

export const sentryTriagePullRequestTemplate = {
  kind: 'workflow_template',
  schemaVersion: '1',
  id: 'sentry-triage-pr',
  version: 1,
  title: 'Sentry incident triage -> PR',
  summary:
    'Triage a production Sentry error, decide whether it should be closed or fixed, and open a pull request when a code change is warranted.',
  description:
    'This template is optimized for production application errors where Cortex can read Sentry context, inspect the repo, patch code, run tests, and either close the issue or open a PR for human merge.',
  tags: ['incident-response', 'sentry', 'triage', 'pr'],
  trigger: {
    kind: 'event',
    source: 'sentry',
    eventTypes: ['issue.created', 'issue.regressed'],
    dedupeKeyTemplate: '{{payload.issue.id}}:{{payload.event.id}}',
    filters: {
      project: ['web', 'api'],
      environment: ['production'],
      level: ['error', 'fatal'],
    },
  },
  initialStageId: 'ingest_alert',
  artifacts: [
    {
      key: 'sentry_event',
      kind: 'event',
      title: 'Normalized Sentry event payload',
      required: true,
      cardinality: 'one',
      retention: 'workflow',
      producedBy: ['ingest_alert'],
      consumedBy: ['collect_context'],
      schema: {
        type: 'object',
        required: ['issueId', 'eventId', 'title', 'environment'],
      },
    },
    {
      key: 'incident_record',
      kind: 'incident',
      title: 'Incident run record',
      required: true,
      cardinality: 'one',
      retention: 'workflow',
      producedBy: ['ingest_alert'],
      consumedBy: ['collect_context', 'triage_incident', 'close_issue', 'open_pr'],
    },
    {
      key: 'context_bundle',
      kind: 'trace_bundle',
      title: 'Logs, stacktrace, blame, and deploy context bundle',
      required: true,
      cardinality: 'one',
      retention: 'workflow',
      producedBy: ['collect_context'],
      consumedBy: ['triage_incident', 'plan_fix', 'implement_fix', 'review_fix'],
    },
    {
      key: 'triage_note',
      kind: 'note',
      title: 'Root-cause hypothesis and disposition note',
      required: true,
      cardinality: 'one',
      retention: 'workflow',
      producedBy: ['triage_incident'],
      consumedBy: ['human_triage_gate', 'plan_fix', 'close_issue'],
    },
    {
      key: 'fix_plan',
      kind: 'plan',
      title: 'Fix plan with affected files, tests, and rollback note',
      required: false,
      cardinality: 'one',
      retention: 'workflow',
      producedBy: ['plan_fix'],
      consumedBy: ['implement_fix'],
    },
    {
      key: 'patch_branch',
      kind: 'patch',
      title: 'Branch containing the proposed fix',
      required: false,
      cardinality: 'one',
      retention: 'workflow',
      producedBy: ['implement_fix'],
      consumedBy: ['review_fix', 'validate_fix', 'open_pr'],
    },
    {
      key: 'test_report',
      kind: 'test_report',
      title: 'Targeted validation report for the fix',
      required: false,
      cardinality: 'one',
      retention: 'workflow',
      producedBy: ['validate_fix'],
      consumedBy: ['open_pr'],
    },
    {
      key: 'review_report',
      kind: 'review_report',
      title: 'Structured review result for the proposed patch',
      required: false,
      cardinality: 'one',
      retention: 'workflow',
      producedBy: ['review_fix'],
      consumedBy: ['validate_fix', 'open_pr'],
    },
    {
      key: 'pull_request',
      kind: 'pull_request',
      title: 'Opened pull request for the incident fix',
      required: false,
      cardinality: 'one',
      retention: 'forever',
      producedBy: ['open_pr'],
    },
    {
      key: 'closure_note',
      kind: 'closure_note',
      title: 'Issue closure note when no code change is needed',
      required: false,
      cardinality: 'one',
      retention: 'forever',
      producedBy: ['close_issue'],
    },
  ],
  stages: [
    {
      id: 'ingest_alert',
      title: 'Ingest alert',
      kind: 'ingest',
      executor: 'system',
      summary:
        'Normalize the incoming Sentry payload, create an incident record, and dedupe repeated alerts.',
      produces: ['sentry_event', 'incident_record'],
      retryPolicy: {
        maxAttempts: 3,
        initialBackoffMs: 10_000,
        maxBackoffMs: 60_000,
        retryOn: ['network_timeout', 'rate_limited'],
      },
      escalationPolicy: {
        afterAttempts: 3,
        setRunStatus: 'blocked',
        notify: ['operator', 'incident_channel'],
        summary: 'Could not normalize or persist the Sentry payload.',
      },
    },
    {
      id: 'collect_context',
      title: 'Collect repo and deploy context',
      kind: 'gather',
      executor: 'agent',
      summary:
        'Pull stacktrace, related logs, recent deploy details, blame context, and linked issue history into one evidence bundle.',
      dependsOn: ['ingest_alert'],
      consumes: ['sentry_event', 'incident_record'],
      produces: ['context_bundle'],
      runtimeAssignment: {
        strategy: 'prefer',
        allowedRuntimes: ['claude-code', 'codex'],
        preferredRuntimes: ['claude-code', 'codex'],
        capabilityRequirements: [
          { capability: 'read_sentry', importance: 'required', reason: 'Need incident data.' },
          { capability: 'read_repo', importance: 'required', reason: 'Need code context.' },
          { capability: 'read_git', importance: 'required', reason: 'Need blame and commit history.' },
          { capability: 'read_deploy_state', importance: 'preferred', reason: 'Need recent deploy correlation.' },
          { capability: 'attach_evidence', importance: 'required', reason: 'Need a durable context bundle.' },
        ],
        sticky: true,
      },
      retryPolicy: {
        maxAttempts: 2,
        initialBackoffMs: 15_000,
        retryOn: ['network_timeout', 'transient_api_error'],
      },
      escalationPolicy: {
        afterAttempts: 2,
        setRunStatus: 'needs_context',
        notify: ['operator'],
        summary: 'Context collection is incomplete; operator input or credentials may be missing.',
        createApproval: true,
      },
    },
    {
      id: 'triage_incident',
      title: 'Triage incident',
      kind: 'triage',
      executor: 'agent',
      summary:
        'Classify the incident as fixable, ignorable, duplicate, or human-escalation-worthy and write the triage note.',
      dependsOn: ['collect_context'],
      consumes: ['incident_record', 'context_bundle'],
      produces: ['triage_note'],
      runtimeAssignment: {
        strategy: 'prefer',
        allowedRuntimes: ['claude-code', 'codex'],
        preferredRuntimes: ['claude-code', 'codex'],
        capabilityRequirements: [
          { capability: 'read_sentry', importance: 'required', reason: 'Need incident details.' },
          { capability: 'read_repo', importance: 'required', reason: 'Need code and ownership context.' },
          { capability: 'write_issue_tracker', importance: 'preferred', reason: 'May annotate the incident.' },
        ],
        sticky: true,
      },
      decisions: [
        {
          id: 'triage_disposition',
          title: 'Incident disposition',
          summary: 'Choose whether to close, fix, or escalate the incident.',
          mode: 'single',
          required: true,
          decidedBy: 'agent',
          evidenceKinds: ['sentry_event', 'stacktrace', 'trace', 'log', 'commit', 'note'],
          options: [
            {
              id: 'close_duplicate',
              label: 'Close as duplicate / already fixed',
              description: 'The evidence matches an already-known or already-fixed issue.',
              nextStageId: 'close_issue',
            },
            {
              id: 'close_expected',
              label: 'Close as expected / not actionable',
              description: 'The error is noisy, benign, or not worth a code change.',
              nextStageId: 'close_issue',
            },
            {
              id: 'fix_in_branch',
              label: 'Patch and open PR',
              description: 'A repo change is warranted and can be validated in isolation.',
              nextStageId: 'plan_fix',
              recommended: true,
            },
            {
              id: 'escalate_human',
              label: 'Escalate to human',
              description: 'The risk or ambiguity is high enough that an operator should decide next steps.',
              nextStageId: 'human_triage_gate',
            },
          ],
        },
      ],
      retryPolicy: {
        maxAttempts: 2,
      },
      escalationPolicy: {
        afterAttempts: 2,
        setRunStatus: 'waiting_for_human',
        notify: ['operator'],
        summary: 'The incident could not be classified with sufficient confidence.',
        createApproval: true,
      },
    },
    {
      id: 'human_triage_gate',
      title: 'Human triage gate',
      kind: 'approval',
      executor: 'human',
      summary:
        'Require operator input when the incident is ambiguous, risky, or crosses product / policy boundaries.',
      dependsOn: ['triage_incident'],
      consumes: ['triage_note', 'incident_record'],
      approvals: [
        {
          id: 'operator_triage_decision',
          policy: 'required',
          title: 'Approve incident path',
          summary: 'Choose whether Cortex should continue toward a fix or close the issue.',
          approverRoles: ['operator', 'oncall'],
          timeoutMinutes: 30,
          onRejectStageId: 'close_issue',
        },
      ],
      escalationPolicy: {
        afterAttempts: 1,
        setRunStatus: 'waiting_for_human',
        notify: ['operator', 'incident_channel'],
        summary: 'Incident disposition is waiting on operator approval.',
      },
    },
    {
      id: 'plan_fix',
      title: 'Plan fix',
      kind: 'plan',
      executor: 'agent',
      summary:
        'Produce a narrow fix plan with touched files, test scope, rollback note, and PR summary skeleton.',
      dependsOn: ['triage_incident'],
      consumes: ['triage_note', 'context_bundle'],
      produces: ['fix_plan'],
      runtimeAssignment: {
        strategy: 'prefer',
        allowedRuntimes: ['claude-code', 'codex'],
        preferredRuntimes: ['claude-code', 'codex'],
        capabilityRequirements: [
          { capability: 'read_repo', importance: 'required', reason: 'Need file-level planning context.' },
          { capability: 'read_git', importance: 'required', reason: 'Need branch and blame context.' },
          { capability: 'run_tests', importance: 'preferred', reason: 'Need to scope validation.' },
        ],
        sticky: true,
      },
    },
    {
      id: 'implement_fix',
      title: 'Implement fix',
      kind: 'build',
      executor: 'agent',
      summary:
        'Create a patch branch, make the minimal code change, and add or update tests for the regression.',
      dependsOn: ['plan_fix'],
      consumes: ['fix_plan', 'context_bundle'],
      produces: ['patch_branch'],
      runtimeAssignment: {
        strategy: 'prefer',
        allowedRuntimes: ['claude-code', 'codex'],
        preferredRuntimes: ['claude-code', 'codex'],
        capabilityRequirements: [
          { capability: 'create_branch', importance: 'required', reason: 'Need an isolated fix branch.' },
          { capability: 'edit_code', importance: 'required', reason: 'Need to patch source files.' },
          { capability: 'create_commit', importance: 'preferred', reason: 'Need a reviewable patch.' },
          { capability: 'run_tests', importance: 'required', reason: 'Need regression validation.' },
        ],
        sticky: true,
      },
      retryPolicy: {
        maxAttempts: 2,
        resetOnManualRetry: true,
      },
      escalationPolicy: {
        afterAttempts: 2,
        setRunStatus: 'blocked',
        notify: ['operator'],
        summary: 'The patch could not be implemented or validated cleanly.',
        createApproval: true,
      },
    },
    {
      id: 'review_fix',
      title: 'Review fix',
      kind: 'review',
      executor: 'agent',
      summary:
        'Run a structured diff review that checks correctness, blast radius, and whether the patch actually addresses the incident.',
      dependsOn: ['implement_fix'],
      consumes: ['patch_branch', 'context_bundle', 'triage_note'],
      produces: ['review_report'],
      runtimeAssignment: {
        strategy: 'prefer',
        allowedRuntimes: ['claude-code', 'codex'],
        preferredRuntimes: ['codex', 'claude-code'],
        capabilityRequirements: [
          { capability: 'review_diff', importance: 'required', reason: 'Need structured diff review.' },
          { capability: 'read_repo', importance: 'required', reason: 'Need surrounding code context.' },
        ],
        sticky: true,
      },
      reviews: [
        {
          id: 'agent_patch_review',
          kind: 'agent',
          title: 'Agent review',
          summary: 'Reject patches that do not materially address the incident.',
          blocking: true,
          checklist: [
            'Does the patch address the stacktrace path?',
            'Is a regression test present when behavior changed?',
            'Is blast radius contained to the smallest necessary scope?',
          ],
        },
      ],
    },
    {
      id: 'validate_fix',
      title: 'Validate fix',
      kind: 'test',
      executor: 'agent',
      summary:
        'Run focused validation for the patch and capture a test report that can travel with the PR.',
      dependsOn: ['review_fix'],
      consumes: ['patch_branch', 'review_report'],
      produces: ['test_report'],
      runtimeAssignment: {
        strategy: 'prefer',
        allowedRuntimes: ['claude-code', 'codex'],
        preferredRuntimes: ['claude-code', 'codex'],
        capabilityRequirements: [
          { capability: 'run_tests', importance: 'required', reason: 'Need validation evidence.' },
          { capability: 'attach_evidence', importance: 'required', reason: 'Need a durable test report.' },
        ],
        sticky: true,
      },
      reviews: [
        {
          id: 'validation_review',
          kind: 'test',
          title: 'Validation review',
          blocking: true,
          checklist: [
            'Did the targeted regression fail before the patch and pass after it?',
            'Were adjacent incident paths checked for obvious regressions?',
          ],
        },
      ],
    },
    {
      id: 'open_pr',
      title: 'Open pull request',
      kind: 'ship',
      executor: 'agent',
      summary:
        'Create a pull request that links the incident, summarizes the fix, and attaches the review and test artifacts.',
      dependsOn: ['validate_fix'],
      consumes: ['patch_branch', 'review_report', 'test_report', 'incident_record'],
      produces: ['pull_request'],
      runtimeAssignment: {
        strategy: 'first_supported',
        allowedRuntimes: ['claude-code', 'codex'],
        preferredRuntimes: ['claude-code', 'codex'],
        capabilityRequirements: [
          { capability: 'create_pr', importance: 'required', reason: 'Need to publish the patch for human merge.' },
          { capability: 'write_issue_tracker', importance: 'preferred', reason: 'Need to link the PR back to the incident.' },
        ],
      },
      terminalOutcomeCode: 'pr_opened',
    },
    {
      id: 'close_issue',
      title: 'Close issue without code change',
      kind: 'close',
      executor: 'agent',
      summary:
        'Close the incident with a written explanation when no code change is needed or an operator rejects a fix path.',
      dependsOn: ['triage_incident'],
      consumes: ['incident_record', 'triage_note'],
      produces: ['closure_note'],
      runtimeAssignment: {
        strategy: 'first_supported',
        allowedRuntimes: ['claude-code', 'codex'],
        preferredRuntimes: ['claude-code', 'codex'],
        capabilityRequirements: [
          { capability: 'close_issue', importance: 'required', reason: 'Need to resolve the incident in the tracker.' },
          { capability: 'write_issue_tracker', importance: 'required', reason: 'Need a closure note.' },
        ],
      },
      terminalOutcomeCode: 'closed_without_code',
    },
  ],
  transitions: [
    { from: 'ingest_alert', to: 'collect_context', when: { kind: 'stage_status', status: 'done' } },
    { from: 'collect_context', to: 'triage_incident', when: { kind: 'stage_status', status: 'done' } },
    { from: 'triage_incident', to: 'close_issue', when: { kind: 'decision', decisionId: 'triage_disposition', optionId: 'close_duplicate' } },
    { from: 'triage_incident', to: 'close_issue', when: { kind: 'decision', decisionId: 'triage_disposition', optionId: 'close_expected' } },
    { from: 'triage_incident', to: 'plan_fix', when: { kind: 'decision', decisionId: 'triage_disposition', optionId: 'fix_in_branch' } },
    { from: 'triage_incident', to: 'human_triage_gate', when: { kind: 'decision', decisionId: 'triage_disposition', optionId: 'escalate_human' } },
    { from: 'human_triage_gate', to: 'plan_fix', when: { kind: 'approval', approvalId: 'operator_triage_decision', status: 'approved' } },
    { from: 'human_triage_gate', to: 'close_issue', when: { kind: 'approval', approvalId: 'operator_triage_decision', status: 'rejected' } },
    { from: 'plan_fix', to: 'implement_fix', when: { kind: 'stage_status', status: 'done' } },
    { from: 'implement_fix', to: 'review_fix', when: { kind: 'stage_status', status: 'done' } },
    { from: 'review_fix', to: 'validate_fix', when: { kind: 'stage_status', status: 'done' } },
    { from: 'validate_fix', to: 'open_pr', when: { kind: 'stage_status', status: 'done' } },
  ],
  outcomes: [
    {
      code: 'pr_opened',
      status: 'done',
      title: 'Pull request opened',
      summary: 'A validated patch branch was promoted to a pull request for human merge.',
    },
    {
      code: 'closed_without_code',
      status: 'done',
      title: 'Issue closed without code change',
      summary: 'The incident was resolved without patching the repo.',
    },
  ],
  metadata: {
    ownerTeam: 'workflow',
    defaultMergePolicy: 'human_merge_required',
    sourceSystem: 'sentry',
  },
} as const satisfies WorkflowTemplate;
