import { sql } from 'drizzle-orm';
import { index, integer, sqliteTable, text } from 'drizzle-orm/sqlite-core';

export const automations = sqliteTable('automations', {
  id: text('id').primaryKey(),
  name: text('name').notNull(),
  owner: text('owner').notNull(),
  projectId: text('project_id'),
  repoPath: text('repo_path').notNull(),
  branch: text('branch').notNull().default('main'),
  runtime: text('runtime').notNull(),
  prompt: text('prompt').notNull(),
  triggerKind: text('trigger_kind', { enum: ['manual', 'cron', 'watch'] }).notNull().default('manual'),
  cronExpr: text('cron_expr'),
  enabled: integer('enabled', { mode: 'boolean' }).notNull().default(true),
  nextRunAt: integer('next_run_at'),
  catchUpPolicy: text('catch_up_policy', {
    enum: ['latest', 'all', 'skip'],
  }).notNull().default('latest'),
  repoConcurrencyLimit: integer('repo_concurrency_limit').notNull().default(1),
  precheckCommand: text('precheck_command'),
  precheckTimeoutMs: integer('precheck_timeout_ms').notNull().default(10_000),
  watchSourceKind: text('watch_source_kind', { enum: ['managed_run', 'packet', 'repository'] }),
  watchSourceId: text('watch_source_id'),
  watchEventTypesJson: text('watch_event_types_json').notNull().default('[]'),
  watchLiteralFilter: text('watch_literal_filter'),
  watchQuietMs: integer('watch_quiet_ms'),
  watchMinIntervalMs: integer('watch_min_interval_ms').notNull().default(0),
  watchBatchWindowMs: integer('watch_batch_window_ms').notNull().default(0),
  watchMaxFiresPerTick: integer('watch_max_fires_per_tick').notNull().default(4),
  watchExpiresAt: integer('watch_expires_at'),
  watchActionKind: text('watch_action_kind', {
    enum: ['dispatch', 'notify', 'steer', 'approval'],
  }).notNull().default('dispatch'),
  watchTargetLaneId: text('watch_target_lane_id'),
  watchCheckpoint: integer('watch_checkpoint').notNull().default(0),
  watchLastFireAt: integer('watch_last_fire_at'),
  lastRunAt: integer('last_run_at'),
  lastRunStatus: text('last_run_status', {
    enum: ['idle', 'running', 'ok', 'error'],
  }).notNull().default('idle'),
  lastLaneId: text('last_lane_id'),
  lastErrorMessage: text('last_error_message'),
  createdAt: text('created_at').notNull().default(sql`(datetime('now'))`),
  updatedAt: text('updated_at').notNull().default(sql`(datetime('now'))`),
}, (table) => ({
  ownerCreatedIdx: index('idx_automations_owner_created').on(table.owner, table.createdAt),
  enabledNextRunIdx: index('idx_automations_enabled_next_run').on(table.enabled, table.nextRunAt),
}));

export const automationFires = sqliteTable('automation_fires', {
  id: text('id').primaryKey(),
  automationId: text('automation_id').notNull().references(() => automations.id, { onDelete: 'cascade' }),
  executionJobId: text('execution_job_id').notNull().unique(),
  source: text('source', { enum: ['scheduled', 'manual'] }).notNull(),
  slotMs: integer('slot_ms'),
  idempotencyKey: text('idempotency_key').notNull().unique(),
  repoPath: text('repo_path').notNull(),
  repoConcurrencyLimit: integer('repo_concurrency_limit').notNull().default(1),
  status: text('status', {
    enum: ['pending', 'leased', 'retrying', 'recovered', 'succeeded', 'parked', 'cancelled'],
  }).notNull().default('pending'),
  scheduledAt: integer('scheduled_at').notNull(),
  persistedAt: integer('persisted_at').notNull(),
  laneId: text('lane_id'),
  missionId: text('mission_id'),
  resultNote: text('result_note'),
  completedAt: integer('completed_at'),
  scheduleDelayMs: integer('schedule_delay_ms'),
  queueDelayMs: integer('queue_delay_ms'),
  executionMs: integer('execution_ms'),
  concurrentCount: integer('concurrent_count'),
  duplicateCount: integer('duplicate_count').notNull().default(0),
  precheckCommand: text('precheck_command'),
  precheckTimeoutMs: integer('precheck_timeout_ms'),
  precheckBypassed: integer('precheck_bypassed', { mode: 'boolean' }).notNull().default(false),
  precheckStatus: text('precheck_status', {
    enum: ['none', 'pending', 'running', 'passed', 'skipped', 'error', 'bypassed'],
  }).notNull().default('none'),
  precheckStartedAt: integer('precheck_started_at'),
  precheckCompletedAt: integer('precheck_completed_at'),
  precheckDurationMs: integer('precheck_duration_ms'),
  precheckExitCode: integer('precheck_exit_code'),
  precheckStdoutTail: text('precheck_stdout_tail'),
  precheckStderrTail: text('precheck_stderr_tail'),
  precheckErrorMessage: text('precheck_error_message'),
  triggerSource: text('trigger_source'),
  sourceEventId: integer('source_event_id'),
  sourceKind: text('source_kind'),
  sourceId: text('source_id'),
  sourceEventType: text('source_event_type'),
  sourceFingerprint: text('source_fingerprint'),
  sourcePayloadJson: text('source_payload_json'),
  actionKind: text('action_kind').notNull().default('dispatch'),
  targetLaneId: text('target_lane_id'),
  updatedAt: integer('updated_at').notNull(),
}, (table) => ({
  historyIdx: index('idx_automation_fires_automation_history').on(table.automationId, table.scheduledAt),
}));
