import { execFileSync, spawnSync } from 'node:child_process';
import { mkdtempSync, rmSync } from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { expect, it, vi } from 'vitest';
import { createDashTmuxSessionSync } from '@/lib/ws-server/dash-terminal-persistence';
// @ts-expect-error -- benchmark modules are intentionally plain JavaScript.
import { BENCH_TMUX_SERVER_NAME, benchTmuxArgs } from '../scripts/bench/tmux-scope.mjs';
// @ts-expect-error -- benchmark modules are intentionally plain JavaScript.
import { cleanupTmuxSessions } from '../scripts/bench/terminal-workload/runtime.mjs';
import { killTmuxSessions, listTmuxSessions, ownedTmuxSessions } from '../scripts/bench/interactions/cleanup.mjs';

const tmuxAvailable = spawnSync('tmux', ['-V'], { stdio: 'ignore' }).status === 0;

it.skipIf(!tmuxAvailable)('queries and cleans the production backing session without touching another server', () => {
  const fixture = mkdtempSync(path.join(os.tmpdir(), 'o8-bench-tmux-test-'));
  const previous = process.env.O8_DASH_TMUX_SERVER_NAME;
  const foreignServer = `${BENCH_TMUX_SERVER_NAME}-foreign`;
  const session = `cortex-dash-${'a'.repeat(32)}`;
  const target = `=${session}`;
  const hasSession = (server: string) => spawnSync('tmux', ['-L', server, 'has-session', '-t', target], {
    stdio: 'ignore',
  }).status === 0;
  try {
    process.env.O8_DASH_TMUX_SERVER_NAME = BENCH_TMUX_SERVER_NAME;
    const createOwned = () => createDashTmuxSessionSync({
      enabled: true, sessionName: session, cols: 93, rows: 24,
      cwd: fixture, shell: '/bin/sh', env: process.env,
    }, { resolveTmuxBinary: () => 'tmux', execFileSync, recordHealth: vi.fn() });
    expect(createOwned()).toBe(true);
    execFileSync('tmux', ['-L', foreignServer, 'new-session', '-d', '-s', session,
      '-x', '70', '-y', '20', '/bin/sh'], { cwd: fixture, stdio: 'ignore' });

    expect(BENCH_TMUX_SERVER_NAME).toMatch(/^o8-bench-\d+-[a-f0-9]{12}$/);
    expect(hasSession(BENCH_TMUX_SERVER_NAME)).toBe(true);
    expect(execFileSync('tmux', benchTmuxArgs('display-message', '-p', '-t', `${target}:`,
      '#{pane_width} #{pane_height}'), { encoding: 'utf8' }).trim()).toBe('93 24');
    expect(execFileSync('tmux', ['-L', foreignServer, 'display-message', '-p', '-t', `${target}:`,
      '#{pane_width} #{pane_height}'], { encoding: 'utf8' }).trim()).toBe('70 20');
    expect(listTmuxSessions()).toEqual([session]);
    expect(ownedTmuxSessions(fixture)).toEqual([session]);

    expect(cleanupTmuxSessions([session])).toEqual([session]);
    expect(hasSession(BENCH_TMUX_SERVER_NAME)).toBe(false);
    expect(hasSession(foreignServer)).toBe(true);
    expect(createOwned()).toBe(true);
    expect(killTmuxSessions([session])).toEqual([session]);
    expect(listTmuxSessions()).toEqual([]);
    expect(hasSession(foreignServer)).toBe(true);
  } finally {
    if (previous === undefined) delete process.env.O8_DASH_TMUX_SERVER_NAME;
    else process.env.O8_DASH_TMUX_SERVER_NAME = previous;
    // Both names were generated by this test process, never operator servers.
    for (const server of [BENCH_TMUX_SERVER_NAME, foreignServer]) {
      spawnSync('tmux', ['-L', server, 'kill-server'], { stdio: 'ignore' });
    }
    rmSync(fixture, { recursive: true, force: true });
  }
}, 15_000);
