import type {
  OrchestratorPacketStatus,
  OrchestratorRuntime,
  WorkspaceOrchestrationPacketBadge,
} from './types';
import type { OrchestratorBackendId } from '@/lib/lane/orchestrator-backends/types';
import { ORCHESTRATOR_RUNTIMES } from './runtime-capabilities';

export { normalizeRuntimeStatusToOrchestratorStatus } from './runtime-status';

/**
 * Resolve the runtime to display for a packet by trusting the lane's
 * sessionKey prefix over `packet.runtime`. Older packets can have stale
 * `packet.runtime` values (e.g. 'codex' on a packet whose lane is actually
 * gemini-backed), so the sessionKey — which is generated by the runtime
 * adapter at session-launch time — is the authoritative source.
 *
 * Falls back to `packet.runtime` when the sessionKey is absent or its prefix
 * is unrecognized, and to `'codex'` only when both are missing.
 */
export function resolveDisplayRuntime(
  packet?: { runtime?: OrchestratorRuntime | string | null; lane?: { sessionKey?: string | null } | null } | null,
): OrchestratorRuntime {
  const sessionKey = packet?.lane?.sessionKey?.trim() ?? '';
  if (sessionKey) {
    const ownedRuntime = (Object.keys(ORCHESTRATOR_RUNTIMES) as OrchestratorRuntime[])
      .find((runtime) => sessionKey.startsWith(`${runtime}-owned:`));
    if (ownedRuntime) return ownedRuntime;
    if (sessionKey.startsWith('gemini-owned:') || sessionKey.startsWith('gemini:')) {
      return 'gemini';
    }
    if (sessionKey.startsWith('claude-code:') || sessionKey.startsWith('claude-code-')) {
      return 'claude-code';
    }
    if (sessionKey.startsWith('opencode-owned:') || sessionKey.startsWith('opencode:')) {
      return 'opencode';
    }
    if (
      sessionKey.startsWith('codex:')
      || sessionKey.startsWith('codex-owned:')
      || sessionKey.startsWith('codex-discovered:')
      || sessionKey.startsWith('codex-live:')
    ) {
      return 'codex';
    }
  }
  const runtime = packet?.runtime;
  if (runtime && ORCHESTRATOR_RUNTIMES[runtime as OrchestratorRuntime]) {
    return runtime as OrchestratorRuntime;
  }
  return 'codex';
}

export interface OrchestratorDisplayTone {
  label: string;
  shortLabel: string;
  color: string;
  background: string;
  border: string;
  dot: string;
}

/** Short-label abbreviations not stored in the capability map (display-only). */
const RUNTIME_SHORT_LABELS: Partial<Record<OrchestratorRuntime, string>> = {
  codex: 'CX',
  'claude-code': 'CC',
  gemini: 'GM',
  opencode: 'OC2',
};

export function orchestratorRuntimeTone(runtime?: OrchestratorRuntime | string | null): OrchestratorDisplayTone {
  const cap = runtime ? ORCHESTRATOR_RUNTIMES[runtime as OrchestratorRuntime] : null;
  if (cap) {
    const color = cap.accentColor;
    // Parse hex to rgba — hex is always 7-char #rrggbb from the map
    const r = parseInt(color.slice(1, 3), 16);
    const g = parseInt(color.slice(3, 5), 16);
    const b = parseInt(color.slice(5, 7), 16);
    return {
      label: cap.label,
      shortLabel: RUNTIME_SHORT_LABELS[runtime as OrchestratorRuntime] ?? cap.shortLabel,
      color,
      background: `rgba(${r}, ${g}, ${b}, 0.12)`,
      border: `rgba(${r}, ${g}, ${b}, 0.2)`,
      dot: color,
    };
  }

  // Unknown runtime — fall back to codex blue
  return {
    label: 'Codex',
    shortLabel: 'CX',
    color: '#2563eb',
    background: 'rgba(37, 99, 235, 0.12)',
    border: 'rgba(37, 99, 235, 0.2)',
    dot: '#2563eb',
  };
}

export function orchestratorStatusTone(status?: OrchestratorPacketStatus | null): OrchestratorDisplayTone {
  switch (status) {
    case 'queued':
      return {
        label: 'Queued',
        shortLabel: 'Q',
        color: '#1d4ed8',
        background: 'rgba(37, 99, 235, 0.1)',
        border: 'rgba(37, 99, 235, 0.18)',
        dot: '#2563eb',
      };
    case 'launching':
      return {
        label: 'Launching',
        shortLabel: 'Go',
        color: '#2563eb',
        background: 'rgba(37, 99, 235, 0.12)',
        border: 'rgba(37, 99, 235, 0.2)',
        dot: '#3b82f6',
      };
    case 'running':
      return {
        label: 'Running',
        shortLabel: 'Run',
        color: '#16a34a',
        background: 'rgba(22, 163, 74, 0.12)',
        border: 'rgba(22, 163, 74, 0.18)',
        dot: '#22c55e',
      };
    case 'awaiting_review':
      return {
        label: 'Reviewing',
        shortLabel: 'Rev',
        color: '#b45309',
        background: 'rgba(245, 158, 11, 0.12)',
        border: 'rgba(245, 158, 11, 0.2)',
        dot: '#f59e0b',
      };
    case 'blocked':
      return {
        label: 'Blocked',
        shortLabel: 'Hold',
        color: '#dc2626',
        background: 'rgba(239, 68, 68, 0.1)',
        border: 'rgba(239, 68, 68, 0.18)',
        dot: '#ef4444',
      };
    case 'recovering':
      return {
        label: 'Recovering',
        shortLabel: 'Fix',
        color: '#7c3aed',
        background: 'rgba(124, 58, 237, 0.12)',
        border: 'rgba(124, 58, 237, 0.2)',
        dot: '#8b5cf6',
      };
    case 'failed':
      return {
        label: 'Failed',
        shortLabel: 'Fail',
        color: '#991b1b',
        background: 'rgba(153, 27, 27, 0.12)',
        border: 'rgba(153, 27, 27, 0.2)',
        dot: '#dc2626',
      };
    case 'released':
      return {
        label: 'Completed',
        shortLabel: 'Done',
        color: '#0f766e',
        background: 'rgba(20, 184, 166, 0.12)',
        border: 'rgba(20, 184, 166, 0.2)',
        dot: '#14b8a6',
      };
    case 'archived':
      return {
        label: 'Archived',
        shortLabel: 'Arc',
        color: '#6b7280',
        background: 'rgba(107, 114, 128, 0.12)',
        border: 'rgba(107, 114, 128, 0.18)',
        dot: '#94a3b8',
      };
    case 'draft':
    case 'idle':
    default:
      return {
        label: 'Waiting',
        shortLabel: 'Wait',
        color: '#64748b',
        background: 'rgba(148, 163, 184, 0.12)',
        border: 'rgba(148, 163, 184, 0.2)',
        dot: '#94a3b8',
      };
  }
}

export function adHocLaneTitle(kind?: 'chat' | 'llm-chat' | 'terminal' | 'canvas' | 'orchestrator' | 'fleet-canvas') {
  if (kind === 'terminal') return 'Terminal';
  if (kind === 'canvas') return 'Inspector';
  if (kind === 'fleet-canvas') return 'Canvas';
  if (kind === 'orchestrator') return 'Orchestrator';
  if (kind === 'chat') return 'Agent';
  return 'Assistant';
}

export function laneDisplayTitle(
  packet?: Pick<WorkspaceOrchestrationPacketBadge, 'title'> | null,
  kind?: 'chat' | 'llm-chat' | 'terminal' | 'canvas' | 'orchestrator' | 'fleet-canvas',
) {
  const title = packet?.title?.trim();
  return title || adHocLaneTitle(kind);
}

/**
 * Canonical runtime → human label. The single source of truth for naming a
 * runtime in the UI ("Codex" / "Claude Code" / "Gemini" / "OpenCode 2"). Never
 * returns a raw id; an unknown/empty runtime yields the generic 'Agent'.
 */
export function runtimeDisplayLabel(runtime?: OrchestratorRuntime | string | null): string {
  const cap = runtime ? ORCHESTRATOR_RUNTIMES[runtime as OrchestratorRuntime] : null;
  return cap?.label ?? 'Agent';
}

/**
 * Canonical agent/session display label. **Never returns a raw id or prefix** —
 * the worst case is the runtime's human label ("Codex") or 'Agent'. Use this
 * everywhere a session/agent needs a name (tab titles, agent tiles, sub-agent
 * rows) so the fallback lives in ONE place and can't drift into id-slicing
 * (`sessionKey.split(':').pop()?.slice(0, 12)` on an owned key yields the
 * literal "codex-owned-", the recurring leak this prevents by construction).
 */
export function agentDisplayLabel(input: {
  name?: string | null;
  title?: string | null;
  sessionKey?: string | null;
  runtime?: OrchestratorRuntime | string | null;
}): string {
  const explicit = input.name?.trim() || input.title?.trim();
  if (explicit) return explicit;
  const runtime = input.runtime
    ?? (input.sessionKey ? resolveDisplayRuntime({ lane: { sessionKey: input.sessionKey } }) : null);
  return runtimeDisplayLabel(runtime);
}

function openClawAgentName(agent?: string | null): string {
  const normalized = agent?.trim();
  if (!normalized) return 'Mister';
  if (normalized === 'main' || normalized === 'main-public' || normalized === 'mister-scribe') return 'Mister';
  return normalized;
}

export function orchestratorBackendDisplayLabel(input: {
  backend?: OrchestratorBackendId | string | null;
  agent?: string | null;
}): string | null {
  switch (input.backend) {
    case 'hermes':
      return 'Hermes';
    case 'openclaw': {
      const agentId = input.agent?.trim() || 'main';
      return `OpenClaw · ${openClawAgentName(agentId)} · ${agentId}`;
    }
    case 'fable':
      return 'Fable';
    case 'collide':
      return 'Collide';
    case 'codex':
      return 'Codex';
    case 'claude':
      return 'Claude Code';
    case 'acp':
      return 'ACP';
    case 'o8':
      return 'o8';
    default:
      return null;
  }
}
