/**
 * Injectable in-page agent for the NATIVE browser-view child window
 * (docs/native-browser-webview-spec.md, Stage 2).
 *
 * Unlike `page-agent.ts` — which runs in o8's OWN window and reaches INTO an
 * `iframe[data-o8-browser]` via `contentDocument` — this agent is injected
 * DIRECTLY into the browser-view page (the user's localhost app, real origin)
 * by the native host via `WebviewWindowBuilder::initialization_script`. So it
 * operates on its OWN `document`: no iframe pick, no cross-origin guard, no
 * proxy-URL unwrap. Same verb surface (`window.__o8BrowserAgent` with
 * read/click/type/probe/grab) so the o8_browser_* eval bridge is identical.
 *
 * SECURITY (see `native_browser_view_security` memory): the browser-view page is
 * UNTRUSTED arbitrary localhost content and deliberately has NO Tauri capability
 * — `__TAURI_INTERNALS__` is never injected there, so this agent can NOT reach
 * any o8 host command (master_key_get, agent_run, …). The native host evals into
 * the page (host→page needs no IPC); DOM results return via a narrow cid-only
 * callback wired in Stage 4, never via the IPC bridge.
 *
 * NO-DRIFT: the two complex, drift-prone pieces — `selectorFor` and
 * `buildGrabbedElement` — are pulled in as the SAME injectable source strings
 * the engine grab uses (`SELECTOR_FOR_SOURCE`, `GRAB_PAYLOAD_SOURCE`), derived
 * from the real functions via `.toString()`. The verbs + ghost cursor are short
 * and hand-written in the template so a minifier can never rename a reference out
 * from under them. `native-agent-source.test.ts` locks the shape.
 */

import { SELECTOR_FOR_SOURCE } from '@/lib/browser/selector';
import { GRAB_PAYLOAD_SOURCE } from '@/lib/browser/grab';

/**
 * Self-contained IIFE that installs `window.__o8BrowserAgent` in the page it is
 * injected into. Idempotent. References only page globals (document, window,
 * location, CSS) plus the injected `selectorFor` / `buildGrabbedElement`.
 */
export const NATIVE_BROWSER_AGENT_SOURCE = [
  '(function () {',
  "  if (typeof window === 'undefined' || window.__o8BrowserAgent) return;",
  '',
  '  // ── no-drift shared algorithms ──',
  SELECTOR_FOR_SOURCE,
  GRAB_PAYLOAD_SOURCE,
  '',
  '  // ── helpers ──',
  '  function labelFor(el) {',
  "    var aria = el.getAttribute('aria-label');",
  '    if (aria) return aria;',
  "    var value = el.placeholder || '';",
  "    var text = (el.textContent || '').trim().replace(/\\s+/g, ' ');",
  "    return (text || value || el.getAttribute('title') || '').slice(0, 80);",
  '  }',
  '',
  '  // ── ghost cursor (the spectator layer — one per page, reused) ──',
  '  var cursorState = null;',
  '  function ensureCursor() {',
  '    if (cursorState && document.body && document.body.contains(cursorState.cursor)) return cursorState;',
  '    if (!document.body) return null;',
  "    var cursor = document.createElement('div');",
  "    cursor.setAttribute('data-o8-agent-cursor', 'true');",
  "    cursor.setAttribute('style', [",
  "      'position:fixed;left:0;top:0;width:16px;height:16px;border-radius:50%',",
  "      'background:rgba(245,158,11,0.9);border:2px solid rgba(255,255,255,0.95)',",
  "      'box-shadow:0 0 0 4px rgba(245,158,11,0.22), 0 2px 10px rgba(0,0,0,0.4)',",
  "      'z-index:2147483600;pointer-events:none;opacity:0;transform:translate(-50%,-50%)',",
  "      'transition:left 320ms cubic-bezier(0.22,1,0.36,1),top 320ms cubic-bezier(0.22,1,0.36,1),opacity 220ms ease-out',",
  "    ].join(';'));",
  "    var ripple = document.createElement('div');",
  "    ripple.setAttribute('data-o8-agent-cursor-ripple', 'true');",
  "    ripple.setAttribute('style', [",
  "      'position:fixed;left:0;top:0;width:16px;height:16px;border-radius:50%',",
  "      'border:2px solid rgba(245,158,11,0.7)',",
  "      'z-index:2147483599;pointer-events:none;opacity:0;transform:translate(-50%,-50%)',",
  "    ].join(';'));",
  '    document.body.appendChild(cursor);',
  '    document.body.appendChild(ripple);',
  '    cursorState = { cursor: cursor, ripple: ripple, hideTimer: null };',
  '    return cursorState;',
  '  }',
  '  function paintCursor(x, y) {',
  '    try {',
  '      var state = ensureCursor();',
  '      if (!state) return;',
  "      var left = Math.round(x) + 'px';",
  "      var top = Math.round(y) + 'px';",
  "      state.cursor.style.opacity = '1';",
  '      state.cursor.style.left = left;',
  '      state.cursor.style.top = top;',
  '      state.ripple.style.left = left;',
  '      state.ripple.style.top = top;',
  "      if (typeof state.ripple.animate === 'function') {",
  '        state.ripple.animate(',
  "          [{ transform: 'translate(-50%,-50%) scale(0.7)', opacity: 0.8 }, { transform: 'translate(-50%,-50%) scale(3.2)', opacity: 0 }],",
  "          { duration: 520, easing: 'ease-out' },",
  '        );',
  '      }',
  '      if (state.hideTimer) clearTimeout(state.hideTimer);',
  "      state.hideTimer = setTimeout(function () { state.cursor.style.opacity = '0'; }, 2400);",
  '    } catch (e) { /* theater is best-effort */ }',
  '  }',
  '',
  '  // ── verbs (operate on this page document directly) ──',
  '  function read(args) {',
  '    args = args || {};',
  '    var root = args.selector ? (document.querySelector(args.selector) || document.body) : document.body;',
  "    if (!root) return { ok: false, error: 'page has no body yet' };",
  '    var maxChars = Math.min(14000, Math.max(400, args.maxChars || 6000));',
  "    var text = (root.innerText || root.textContent || '').replace(/\\n{3,}/g, '\\n\\n');",
  '    var interactive = [];',
  '    var nodes = root.querySelectorAll(\'a[href], button, input, textarea, select, [role="button"], [role="link"], [onclick]\');',
  '    for (var i = 0; i < nodes.length; i++) {',
  '      if (interactive.length >= 60) break;',
  '      var el = nodes[i];',
  '      var rect = el.getBoundingClientRect();',
  '      if (rect.width === 0 || rect.height === 0) continue;',
  '      interactive.push({ selector: selectorFor(el), tag: el.tagName.toLowerCase(), label: labelFor(el) });',
  '    }',
  '    return {',
  '      ok: true,',
  '      url: location.href,',
  '      title: document.title,',
  "      text: text.length > maxChars ? text.slice(0, maxChars) + '\\u2026 [truncated ' + (text.length - maxChars) + ' chars]' : text,",
  '      interactive: interactive,',
  '    };',
  '  }',
  '',
  '  function click(args) {',
  '    args = args || {};',
  '    var el = args.selector ? document.querySelector(args.selector) : null;',
  "    if (!el) return { ok: false, error: 'no element matches ' + args.selector };",
  '    var rect = el.getBoundingClientRect();',
  '    var x = rect.left + rect.width / 2;',
  '    var y = rect.top + rect.height / 2;',
  '    paintCursor(x, y);',
  '    var opts = { bubbles: true, cancelable: true, clientX: x, clientY: y, view: window };',
  "    try { el.dispatchEvent(new PointerEvent('pointerdown', opts)); } catch (e) {}",
  "    el.dispatchEvent(new MouseEvent('mousedown', opts));",
  "    try { el.dispatchEvent(new PointerEvent('pointerup', opts)); } catch (e) {}",
  "    el.dispatchEvent(new MouseEvent('mouseup', opts));",
  '    if (typeof el.click === \'function\') el.click();',
  '    return { ok: true, clicked: args.selector, label: labelFor(el) };',
  '  }',
  '',
  '  function type(args) {',
  '    args = args || {};',
  '    var el = args.selector ? document.querySelector(args.selector) : null;',
  "    if (!el) return { ok: false, error: 'no element matches ' + args.selector };",
  '    var rect = el.getBoundingClientRect();',
  '    paintCursor(rect.left + Math.min(24, rect.width / 2), rect.top + rect.height / 2);',
  '    el.focus();',
  "    var proto = el.tagName === 'TEXTAREA' ? window.HTMLTextAreaElement.prototype : window.HTMLInputElement.prototype;",
  "    var desc = Object.getOwnPropertyDescriptor(proto, 'value');",
  '    var setter = desc && desc.set;',
  "    if (setter) setter.call(el, args.text); else el.value = args.text;",
  "    el.dispatchEvent(new Event('input', { bubbles: true }));",
  "    el.dispatchEvent(new Event('change', { bubbles: true }));",
  '    if (args.submit) {',
  "      el.dispatchEvent(new KeyboardEvent('keydown', { key: 'Enter', bubbles: true, cancelable: true }));",
  "      var form = el.closest('form');",
  "      if (form && typeof form.requestSubmit === 'function') form.requestSubmit();",
  '    }',
  "    return { ok: true, typed: (args.text || '').length, into: args.selector };",
  '  }',
  '',
  '  function probe(args) {',
  '    args = args || {};',
  '    var el = args.selector ? document.querySelector(args.selector) : null;',
  '    if (!el) return { ok: false, pending: true };',
  "    if (args.text && (el.textContent || '').indexOf(args.text) === -1) return { ok: false, pending: true };",
  '    return { ok: true, found: args.selector };',
  '  }',
  '',
  '  function grab(args) {',
  '    args = args || {};',
  '    var el = args.selector ? document.querySelector(args.selector) : null;',
  "    if (!el) return { ok: false, error: 'no element matches ' + args.selector };",
  '    var rect = el.getBoundingClientRect();',
  '    paintCursor(rect.left + rect.width / 2, rect.top + rect.height / 2);',
  '    return { ok: true, element: buildGrabbedElement(el, selectorFor(el)) };',
  '  }',
  '',
  '  // ── Design Mode freehand draw (native pages stay live) ──',
  '  var __designDraw = null;',
  '  function stopDesignDraw() { if (!__designDraw) return; var s = __designDraw; window.removeEventListener("keydown", s.key, true); s.canvas.remove(); s.hint.remove(); if (s.composer) s.composer.remove(); __designDraw = null; }',
  '  function startDesignDraw(args) {',
  '    if (!args || args.on !== true) { stopDesignDraw(); return { ok: true, armed: false }; } stopDesignDraw(); if (!document.body) return { ok: false, error: "page has no body yet" };',
  '    var canvas = document.createElement("canvas"), hint = document.createElement("div"), ctx, points = [], drawing = false, composer = null;',
  '    canvas.setAttribute("data-o8-design-draw", "true"); canvas.setAttribute("style", "position:fixed;inset:0;width:100vw;height:100vh;z-index:2147483645;cursor:crosshair;touch-action:none;");',
  '    hint.setAttribute("style", "position:fixed;top:16px;left:50%;transform:translateX(-50%);z-index:2147483646;padding:9px 13px;border:1px solid rgba(255,255,255,.12);border-radius:10px;background:#1c1c1e;color:#f5f5f7;font:600 12px -apple-system,BlinkMacSystemFont,sans-serif;pointer-events:none;"); hint.textContent = "Draw on the page · Esc to exit"; document.body.appendChild(canvas); document.body.appendChild(hint);',
  '    function size() { var d = window.devicePixelRatio || 1; canvas.width = innerWidth * d; canvas.height = innerHeight * d; ctx = canvas.getContext("2d"); ctx.scale(d, d); ctx.strokeStyle = "#FF5A1F"; ctx.lineWidth = 2.5; ctx.lineCap = "round"; ctx.lineJoin = "round"; ctx.globalAlpha = .9; } size();',
  '    function submit() { var input = composer && composer.querySelector("textarea"), text = input && input.value.trim(); if (!text || !points.length) return; var xs = points.map(function(p){return p.x;}), ys = points.map(function(p){return p.y;}), rect = { left: Math.min.apply(null,xs), top: Math.min.apply(null,ys), width: Math.max.apply(null,xs)-Math.min.apply(null,xs), height: Math.max.apply(null,ys)-Math.min.apply(null,ys) }, seen = {}, elements = []; canvas.style.pointerEvents = "none"; points.forEach(function(p) { if (elements.length >= 4) return; var el = document.elementFromPoint(p.x,p.y), key = el && selectorFor(el); if (el && key && !seen[key]) { seen[key] = true; elements.push({ selector:key, tag:el.tagName.toLowerCase(), text:(el.textContent||"").replace(/\\s+/g," ").trim().slice(0,80) }); } }); canvas.style.pointerEvents = "auto"; window.__o8DesignDrawResult = { ok:true, text:text, rect:rect, points:points, elements:elements }; }',
  '    // Composer is built with createElement ONLY — hardened pages (o8.run)',
  '    // enforce Trusted Types via CSP, and an innerHTML assignment THROWS',
  '    // silently inside the pointerup handler (live-hit 2026-07-12: ink drew,',
  '    // composer never appeared, mode stuck).',
  '    function finish() { if (!drawing || points.length < 2) return; drawing = false; var xs = points.map(function(p){return p.x;}), ys = points.map(function(p){return p.y;}), x = (Math.min.apply(null,xs) + Math.max.apply(null,xs)) / 2, y = Math.min(innerHeight - 68, Math.max(12, Math.max.apply(null,ys) + 12)); composer = document.createElement("div"); composer.setAttribute("data-o8-design-composer", "true"); composer.setAttribute("style", "position:fixed;left:"+x+"px;top:"+y+"px;transform:translateX(-50%);z-index:2147483646;display:flex;gap:8px;padding:8px;border:1px solid rgba(255,255,255,.12);border-radius:12px;background:#1c1c1e;box-shadow:0 12px 32px rgba(0,0,0,.32);"); var input = document.createElement("textarea"); input.rows = 1; input.placeholder = "Describe what to change here…"; input.setAttribute("style", "width:230px;resize:none;border:0;outline:0;background:transparent;color:#f5f5f7;font:13px -apple-system,BlinkMacSystemFont,sans-serif"); var button = document.createElement("button"); button.type = "button"; button.textContent = "Send"; button.setAttribute("style", "border:0;border-radius:8px;background:#FF5A1F;color:#fff;padding:0 11px;font:600 12px -apple-system,BlinkMacSystemFont,sans-serif;cursor:pointer"); composer.appendChild(input); composer.appendChild(button); document.body.appendChild(composer); __designDraw.composer = composer; button.addEventListener("click", submit); input.addEventListener("keydown", function(e){ if (e.key === "Enter" && !e.shiftKey) { e.preventDefault(); submit(); } e.stopPropagation(); }); setTimeout(function(){ input.focus(); }, 30); }',
  '    canvas.addEventListener("pointerdown", function(e){ if (e.button !== 0) return; if (composer) { composer.remove(); composer=null; __designDraw.composer=null; ctx.clearRect(0,0,innerWidth,innerHeight); } drawing=true; points=[{x:e.clientX,y:e.clientY}]; canvas.setPointerCapture(e.pointerId); ctx.beginPath(); ctx.moveTo(e.clientX,e.clientY); e.preventDefault(); }); canvas.addEventListener("pointermove", function(e){ if (!drawing) return; points.push({x:e.clientX,y:e.clientY}); ctx.lineTo(e.clientX,e.clientY); ctx.stroke(); e.preventDefault(); }); canvas.addEventListener("pointerup", function(e){ try { finish(); } catch (err) { window.__o8DesignDrawResult = { ok:false, error:"finish threw: " + String((err && err.message) || err) }; } e.preventDefault(); }); canvas.addEventListener("wheel", function(e){ window.scrollBy({ top:e.deltaY, left:e.deltaX, behavior:"auto" }); e.preventDefault(); }, { passive:false });',
  '    var key = function(e) { if (e.key === "Escape") { window.__o8DesignDrawResult = { ok:false, escaped:true }; stopDesignDraw(); } }; window.addEventListener("keydown", key, true); __designDraw = { canvas:canvas, hint:hint, composer:composer, key:key }; return { ok:true, armed:true };',
  '  }',
  '',
  '',
  '  // ── Design Mode click-to-grab (Stage 4b) ──',
  '  // The operator clicks an element in the native window; the click lands HERE',
  '  // (the native window owns the pointer), so o8\\u2019s main-webview Design Mode',
  '  // overlay can\\u2019t see it. We install an in-page hover-highlight + one-shot',
  '  // click handler that grabs elementFromPoint and POSTs the GrabbedElement back',
  '  // through the same cid-only result channel.',
  '  var __designGrab = null;',
  '  function startDesignGrab() {',
  '    stopDesignGrab();',
  "    var hl = document.createElement('div');",
  "    hl.setAttribute('data-o8-design-highlight', 'true');",
  "    hl.setAttribute('style', 'position:fixed;z-index:2147483646;pointer-events:none;border:2px solid #2563eb;background:rgba(37,99,235,0.08);border-radius:6px;display:none;box-sizing:border-box;transition:left 60ms linear,top 60ms linear,width 60ms linear,height 60ms linear;');",
  '    if (document.body) document.body.appendChild(hl);',
  '    function onMove(e) {',
  '      var t = document.elementFromPoint(e.clientX, e.clientY);',
  "      if (!t || t === hl) { hl.style.display = 'none'; return; }",
  '      var b = t.getBoundingClientRect();',
  "      hl.style.display = 'block'; hl.style.left = b.left + 'px'; hl.style.top = b.top + 'px'; hl.style.width = b.width + 'px'; hl.style.height = b.height + 'px';",
  '    }',
  '    function onClick(e) {',
  '      e.preventDefault(); e.stopPropagation();',
  '      var t = document.elementFromPoint(e.clientX, e.clientY);',
  '      var payload;',
  "      try { payload = t ? { ok: true, element: buildGrabbedElement(t, selectorFor(t)) } : { ok: false, error: 'no element under cursor' }; }",
  '      catch (err) { payload = { ok: false, error: String((err && err.message) || err) }; }',
  '      stopDesignGrab();',
  '      // Store for the host to PULL via browser_view_eval_result. The page can',
  "      // not POST to o8's HTTP server from an HTTPS origin (mixed content), so",
  '      // the native host reads this back instead of the page pushing it.',
  '      try { window.__o8DesignGrabResult = payload; } catch (e2) {}',
  '    }',
  "    document.addEventListener('mousemove', onMove, true);",
  "    document.addEventListener('click', onClick, true);",
  '    __designGrab = { hl: hl, onMove: onMove, onClick: onClick };',
  '  }',
  '  function stopDesignGrab() {',
  '    if (!__designGrab) return;',
  "    document.removeEventListener('mousemove', __designGrab.onMove, true);",
  "    document.removeEventListener('click', __designGrab.onClick, true);",
  '    if (__designGrab.hl && __designGrab.hl.parentNode) __designGrab.hl.parentNode.removeChild(__designGrab.hl);',
  '    __designGrab = null;',
  '  }',
  '',
  '  window.__o8BrowserAgent = { read: read, click: click, type: type, probe: probe, grab: grab, drawmode: startDesignDraw, startDesignGrab: startDesignGrab, stopDesignGrab: stopDesignGrab };',
  '})();',
].join('\n');
