import { readFileSync, existsSync } from 'fs';
import { persistCanonicalChatHistoryRecord } from '@/lib/llm/chat-history-store';

/**
 * Thread auto-titling (Q ruling 2026-07-13): chats name themselves like
 * Cursor's — a short, honest title after the first exchange, refreshed once
 * as the thread develops, generated by the FREE model chain (zero marginal
 * cost) with a pure-code fallback when no key is present. Operator renames
 * are sacred: `titleSource: 'operator'` is never overwritten.
 *
 * File fields written alongside `title`:
 *   titleSource        'code' | 'llm' | 'operator'
 *   autoTitledAtCount  message count when the auto title was last generated
 */

// Same free chain the o8-operator rail rides (provider-config.ts). Re-declared
// here so this fs-level module doesn't import from the app router tree.
const FREE_TITLE_MODELS = [
  'nvidia/nemotron-3-ultra-550b-a55b:free',
  'openai/gpt-oss-120b:free',
];

const TITLE_TIMEOUT_MS = 8000;
/** First auto-title once the thread has a real exchange. */
const MIN_MESSAGES = 2;
/** One refresh pass once the thread has developed past this. */
const REFRESH_AT = 8;
/** A stored title longer than this with no titleSource is a legacy raw-crop
 *  first message — eligible for an upgrade. */
const LEGACY_RAW_TITLE_LENGTH = 64;

const inFlight = new Set<string>();

interface ThreadMessage { role?: unknown; content?: unknown }

function messageText(message: ThreadMessage): string {
  return typeof message.content === 'string' ? message.content : '';
}

/** Pure-code fallback: first sentence-ish of the first user message, cleaned
 *  of markdown noise, capped at a word boundary. */
export function compactTitleFromMessage(text: string): string | null {
  const cleaned = text
    .replace(/```[\s\S]*?```/g, ' ')
    .replace(/!?\[[^\]]*\]\([^)]*\)/g, ' ')
    .replace(/https?:\/\/\S+/g, ' ')
    .replace(/[#*_`>]/g, '')
    .replace(/\s+/g, ' ')
    .trim();
  if (!cleaned) return null;
  const sentence = cleaned.split(/(?<=[.!?])\s/)[0] ?? cleaned;
  const base = sentence.length >= 12 ? sentence : cleaned;
  if (base.length <= 48) return base.replace(/[.!?,;:]+$/, '');
  const cropped = base.slice(0, 48);
  const lastSpace = cropped.lastIndexOf(' ');
  return (lastSpace > 24 ? cropped.slice(0, lastSpace) : cropped).replace(/[.!?,;:]+$/, '');
}

interface AutoTitleDecision {
  run: boolean;
  reason?: 'first' | 'refresh' | 'legacy-upgrade';
}

/** Pure decision logic — exported for the real-path test. */
export function decideAutoTitle(record: {
  title?: unknown;
  titleSource?: unknown;
  autoTitledAtCount?: unknown;
  messageCount: number;
}): AutoTitleDecision {
  if (record.titleSource === 'operator') return { run: false };
  if (record.messageCount < MIN_MESSAGES) return { run: false };
  const title = typeof record.title === 'string' ? record.title.trim() : '';
  const titledAt = typeof record.autoTitledAtCount === 'number' ? record.autoTitledAtCount : 0;
  const isAuto = record.titleSource === 'code' || record.titleSource === 'llm';

  if (!title) return { run: true, reason: 'first' };
  // Legacy raw-crop first-message titles (pre-titler threads) upgrade once.
  if (!record.titleSource && title.length > LEGACY_RAW_TITLE_LENGTH) {
    return { run: true, reason: 'legacy-upgrade' };
  }
  // One refresh pass as the thread develops past the auto title's vintage.
  if (isAuto && record.messageCount >= REFRESH_AT && titledAt < REFRESH_AT) {
    return { run: true, reason: 'refresh' };
  }
  return { run: false };
}

async function llmTitle(firstUser: string, lastAssistant: string): Promise<string | null> {
  const apiKey = process.env.OPENROUTER_API_KEY?.trim();
  if (!apiKey) return null;
  const prompt = [
    'Name this coding-assistant chat thread.',
    'Reply with ONLY the title: 3 to 6 words, plain text, no quotes, no trailing punctuation.',
    'Capture the actual task or topic, not pleasantries.',
    '',
    `First message: ${firstUser.slice(0, 500)}`,
    lastAssistant ? `Latest reply excerpt: ${lastAssistant.slice(0, 300)}` : '',
  ].filter(Boolean).join('\n');

  for (const model of FREE_TITLE_MODELS) {
    const controller = new AbortController();
    const timer = setTimeout(() => controller.abort(), TITLE_TIMEOUT_MS);
    try {
      const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json', Authorization: `Bearer ${apiKey}` },
        body: JSON.stringify({
          model,
          messages: [{ role: 'user', content: prompt }],
          max_tokens: 24,
          temperature: 0.2,
          stream: false,
        }),
        signal: controller.signal,
      });
      if (!response.ok) continue;
      const payload = await response.json() as { choices?: Array<{ message?: { content?: string } }> };
      const raw = payload.choices?.[0]?.message?.content?.trim() ?? '';
      // Strip wrapping quotes + reasoning-model preamble leakage; keep one line.
      const line = raw.split('\n').map((l) => l.trim()).filter(Boolean).pop() ?? '';
      const cleaned = line.replace(/^["'`]+|["'`.]+$/g, '').trim();
      if (cleaned && cleaned.length >= 3 && cleaned.length <= 72) return cleaned;
    } catch {
      // timeout / network — try the next free model
    } finally {
      clearTimeout(timer);
    }
  }
  return null;
}

/**
 * Fire-and-forget: reads the thread file, decides, generates, writes back.
 * Re-reads before write so a concurrent operator rename always wins.
 */
export function maybeQueueThreadAutoTitle(filePath: string): void {
  if (inFlight.has(filePath)) return;
  inFlight.add(filePath);
  void (async () => {
    try {
      if (!existsSync(filePath)) return;
      const data = JSON.parse(readFileSync(filePath, 'utf-8')) as Record<string, unknown>;
      const messages = Array.isArray(data.messages) ? data.messages as ThreadMessage[] : [];
      const decision = decideAutoTitle({
        title: data.title,
        titleSource: data.titleSource,
        autoTitledAtCount: data.autoTitledAtCount,
        messageCount: messages.length,
      });
      if (!decision.run) return;

      const firstUser = messageText(messages.find((m) => m.role === 'user') ?? {});
      if (!firstUser.trim()) return;
      const lastAssistant = messageText([...messages].reverse().find((m) => m.role === 'assistant') ?? {});

      const generated = await llmTitle(firstUser, lastAssistant);
      const fallback = compactTitleFromMessage(firstUser);
      const nextTitle = generated ?? fallback;
      if (!nextTitle) return;
      // An LLM miss must not clobber an existing title with a same-quality
      // code crop — only fill code titles into blank/legacy slots once.
      if (!generated && decision.reason === 'refresh') return;

      const fresh = JSON.parse(readFileSync(filePath, 'utf-8')) as Record<string, unknown>;
      if (fresh.titleSource === 'operator') return;
      fresh.title = nextTitle;
      fresh.titleSource = generated ? 'llm' : 'code';
      fresh.autoTitledAtCount = messages.length;
      const tabId = filePath.split('/').pop()?.replace(/\.json$/, '');
      if (tabId) persistCanonicalChatHistoryRecord(
        tabId,
        fresh as { messages: unknown[]; [key: string]: unknown },
      );
      console.log(`[thread-auto-title] ${decision.reason}: "${nextTitle}" (${generated ? 'llm' : 'code'})`);
    } catch {
      // best-effort — never break the persist path
    } finally {
      inFlight.delete(filePath);
    }
  })();
}
