import 'dotenv/config';

/**
 * Boot-time environment validation for the o8 license server.
 *
 * Every required variable is read + validated here. If anything is missing we
 * throw a single, clear error at import time so the process fails fast on
 * Railway rather than 500ing on the first webhook. Optional vars get sane
 * defaults.
 */

function required(name: string): string {
  const value = process.env[name];
  if (!value || !value.trim()) {
    throw new Error(
      `[license-server] Missing required env var: ${name}. ` +
        `Set it in Railway (or .env for local dev). See .env.example.`,
    );
  }
  return value.trim();
}

function optional(name: string, fallback: string): string {
  const value = process.env[name];
  return value && value.trim() ? value.trim() : fallback;
}

/**
 * The Ed25519 PRIVATE key (PKCS8 PEM) used to sign license JWTs. Generated by
 * `npm run gen-keys`. Railway commonly stores multi-line secrets with literal
 * `\n` sequences, so we normalize those back to real newlines.
 */
function loadPrivateKeyPem(): string {
  const raw = required('LICENSE_PRIVATE_KEY');
  const pem = raw.includes('\\n') ? raw.replace(/\\n/g, '\n') : raw;
  if (!pem.includes('BEGIN PRIVATE KEY')) {
    throw new Error(
      '[license-server] LICENSE_PRIVATE_KEY must be a PKCS8 PEM ' +
        '(-----BEGIN PRIVATE KEY-----). Run `npm run gen-keys` to generate one.',
    );
  }
  return pem;
}

export const env = {
  // Stripe
  STRIPE_SECRET_KEY: required('STRIPE_SECRET_KEY'),
  STRIPE_WEBHOOK_SECRET: required('STRIPE_WEBHOOK_SECRET'),
  STRIPE_PRICE_SOLO: required('STRIPE_PRICE_SOLO'),
  STRIPE_PRICE_TEAM: required('STRIPE_PRICE_TEAM'),
  // The $150 one-time "Founding Operator" price. Optional so the server still
  // boots before it exists in Stripe; the webhook also recognizes the purchase
  // via session.metadata.productType === 'founding'.
  STRIPE_PRICE_FOUNDER: optional('STRIPE_PRICE_FOUNDER', ''),

  // Signing
  LICENSE_PRIVATE_KEY: loadPrivateKeyPem(),

  // Database
  DATABASE_URL: required('DATABASE_URL'),

  // Issuance
  ISSUER: optional('ISSUER', 'o8-license'),

  // Admin guard for manual issue/revoke endpoints (mint + revoke licenses).
  ADMIN_TOKEN: required('ADMIN_TOKEN'),

  // Scoped READ-ONLY token for the usage-analytics dashboard (GET
  // /admin/analytics). Separate from ADMIN_TOKEN so the desktop only ever holds
  // a credential that can read aggregate stats — never mint/revoke a license.
  // Optional: when unset, the analytics endpoint falls back to requiring the
  // full ADMIN_TOKEN. Lower blast radius if it ever leaks from a machine.
  ANALYTICS_TOKEN: optional('ANALYTICS_TOKEN', ''),

  // Managed-inference proxy upstream keys (Step 1). OPTIONAL at boot so the
  // service still runs without them — the /v1/* proxy routes return 503 until
  // they're set. These are OUR funded keys; they live ONLY here, never in the
  // desktop build. GEMINI_API_KEY also accepts the GOOGLE_AI_API_KEY alias.
  OPENROUTER_API_KEY: optional('OPENROUTER_API_KEY', ''),
  GEMINI_API_KEY: optional('GEMINI_API_KEY', '') || optional('GOOGLE_AI_API_KEY', ''),

  // Scoped guard for POST /invites/register (the desktop app sends this when it
  // shares a beta invite). Optional — when unset, invite registration is
  // disabled (503) and the rest of the service runs unchanged. Rotate
  // independently of ADMIN_TOKEN; lower blast radius if it leaks from a build.
  INVITE_REGISTER_TOKEN: optional('INVITE_REGISTER_TOKEN', ''),

  // ── Founding Operator (one-time $150 purchase) ──────────────────────────
  // License validity for a founder's minted token. Long-dated (≈10y) because
  // it's a lifetime grant; it's also re-minted on each account fetch, so this
  // is just the offline ceiling.
  FOUNDER_LICENSE_DAYS: Number.parseInt(optional('FOUNDER_LICENSE_DAYS', '3650'), 10),
  // SOFT "what a founder gets" knobs, stamped onto the row at purchase and
  // editable later (finalize the grant by setting these, not by redeploying):
  // prepaid managed-infra credit and the locked monthly rate, both in USD.
  FOUNDER_CREDIT_USD: Number.parseFloat(optional('FOUNDER_CREDIT_USD', '0')),
  FOUNDER_RATE_LOCK_USD: optional('FOUNDER_RATE_LOCK_USD', ''),
  // Soft cap for the cohort — the sell side enforces it; we only log if a
  // purchase lands beyond it. NEVER reject money already taken.
  FOUNDER_CAP: Number.parseInt(optional('FOUNDER_CAP', '100'), 10),

  // Clerk issuer URL (e.g. https://<slug>.clerk.accounts.dev). Used to verify a
  // desktop's Clerk session token on /account/license, so a signed-in user can
  // pull THEIR OWN license — no shared secret shipped in the app. Optional:
  // when unset, /account/license is disabled (503).
  CLERK_ISSUER: optional('CLERK_ISSUER', ''),

  // Welcome email (best-effort, Resend). Optional: when RESEND_API_KEY is unset
  // the mail is skipped (Stripe sends its own receipt, and the license is
  // delivered by account-fetch on sign-in regardless).
  RESEND_API_KEY: optional('RESEND_API_KEY', ''),
  EMAIL_FROM: optional('EMAIL_FROM', 'o8 <founding@o8.run>'),

  // HTTP
  PORT: Number.parseInt(optional('PORT', '8080'), 10),
} as const;

export type Env = typeof env;
