import 'dotenv/config';

/**
 * Boot-time environment validation for the o8 license server.
 *
 * Every required variable is read + validated here. If anything is missing we
 * throw a single, clear error at import time so the process fails fast on
 * Railway rather than 500ing on the first webhook. Optional vars get sane
 * defaults.
 */

function required(name: string): string {
  const value = process.env[name];
  if (!value || !value.trim()) {
    throw new Error(
      `[license-server] Missing required env var: ${name}. ` +
        `Set it in Railway (or .env for local dev). See .env.example.`,
    );
  }
  return value.trim();
}

function optional(name: string, fallback: string): string {
  const value = process.env[name];
  return value && value.trim() ? value.trim() : fallback;
}

/**
 * The Ed25519 PRIVATE key (PKCS8 PEM) used to sign license JWTs. Generated by
 * `npm run gen-keys`. Railway commonly stores multi-line secrets with literal
 * `\n` sequences, so we normalize those back to real newlines.
 */
function loadPrivateKeyPem(): string {
  const raw = required('LICENSE_PRIVATE_KEY');
  const pem = raw.includes('\\n') ? raw.replace(/\\n/g, '\n') : raw;
  if (!pem.includes('BEGIN PRIVATE KEY')) {
    throw new Error(
      '[license-server] LICENSE_PRIVATE_KEY must be a PKCS8 PEM ' +
        '(-----BEGIN PRIVATE KEY-----). Run `npm run gen-keys` to generate one.',
    );
  }
  return pem;
}

export const env = {
  // Stripe
  STRIPE_SECRET_KEY: required('STRIPE_SECRET_KEY'),
  STRIPE_WEBHOOK_SECRET: required('STRIPE_WEBHOOK_SECRET'),
  STRIPE_PRICE_SOLO: required('STRIPE_PRICE_SOLO'),
  STRIPE_PRICE_TEAM: required('STRIPE_PRICE_TEAM'),

  // Signing
  LICENSE_PRIVATE_KEY: loadPrivateKeyPem(),

  // Database
  DATABASE_URL: required('DATABASE_URL'),

  // Issuance
  ISSUER: optional('ISSUER', 'o8-license'),

  // Admin guard for manual issue/revoke endpoints
  ADMIN_TOKEN: required('ADMIN_TOKEN'),

  // Scoped guard for POST /invites/register (the desktop app sends this when it
  // shares a beta invite). Optional — when unset, invite registration is
  // disabled (503) and the rest of the service runs unchanged. Rotate
  // independently of ADMIN_TOKEN; lower blast radius if it leaks from a build.
  INVITE_REGISTER_TOKEN: optional('INVITE_REGISTER_TOKEN', ''),

  // HTTP
  PORT: Number.parseInt(optional('PORT', '8080'), 10),
} as const;

export type Env = typeof env;
