import 'dotenv/config';

/**
 * Boot-time environment validation for the o8 license server.
 *
 * Every required variable is read + validated here. If anything is missing we
 * throw a single, clear error at import time so the process fails fast on
 * Railway rather than 500ing on the first webhook. Optional vars get sane
 * defaults.
 */

function required(name: string): string {
  const value = process.env[name];
  if (!value || !value.trim()) {
    throw new Error(
      `[license-server] Missing required env var: ${name}. ` +
        `Set it in Railway (or .env for local dev). See .env.example.`,
    );
  }
  return value.trim();
}

function optional(name: string, fallback: string): string {
  const value = process.env[name];
  return value && value.trim() ? value.trim() : fallback;
}

/**
 * The Ed25519 PRIVATE key (PKCS8 PEM) used to sign license JWTs. Generated by
 * `npm run gen-keys`. Railway commonly stores multi-line secrets with literal
 * `\n` sequences, so we normalize those back to real newlines.
 */
function loadPrivateKeyPem(): string {
  const raw = required('LICENSE_PRIVATE_KEY');
  const pem = raw.includes('\\n') ? raw.replace(/\\n/g, '\n') : raw;
  if (!pem.includes('BEGIN PRIVATE KEY')) {
    throw new Error(
      '[license-server] LICENSE_PRIVATE_KEY must be a PKCS8 PEM ' +
        '(-----BEGIN PRIVATE KEY-----). Run `npm run gen-keys` to generate one.',
    );
  }
  return pem;
}

export const env = {
  // Stripe
  STRIPE_SECRET_KEY: required('STRIPE_SECRET_KEY'),
  STRIPE_WEBHOOK_SECRET: required('STRIPE_WEBHOOK_SECRET'),
  STRIPE_PRICE_SOLO: required('STRIPE_PRICE_SOLO'),
  STRIPE_PRICE_TEAM: required('STRIPE_PRICE_TEAM'),
  // Founding Operator tiered prices (250-cohort): T1 #1-100 $150, T2 #101-200
  // $250, T3 #201-250 $500. Optional so the server boots before they exist in
  // Stripe; the checkout-session creation against these lives in o8-site. The
  // webhook also recognizes the purchase via session.metadata.productType.
  STRIPE_PRICE_FOUNDER_T1: optional('STRIPE_PRICE_FOUNDER_T1', ''),
  STRIPE_PRICE_FOUNDER_T2: optional('STRIPE_PRICE_FOUNDER_T2', ''),
  STRIPE_PRICE_FOUNDER_T3: optional('STRIPE_PRICE_FOUNDER_T3', ''),

  // Signing
  LICENSE_PRIVATE_KEY: loadPrivateKeyPem(),

  // Database
  DATABASE_URL: required('DATABASE_URL'),

  // Issuance
  ISSUER: optional('ISSUER', 'o8-license'),

  // Admin guard for manual issue/revoke endpoints (mint + revoke licenses).
  ADMIN_TOKEN: required('ADMIN_TOKEN'),

  // Scoped READ-ONLY token for the usage-analytics dashboard (GET
  // /admin/analytics). Separate from ADMIN_TOKEN so the desktop only ever holds
  // a credential that can read aggregate stats — never mint/revoke a license.
  // Optional: when unset, the analytics endpoint falls back to requiring the
  // full ADMIN_TOKEN. Lower blast radius if it ever leaks from a machine.
  ANALYTICS_TOKEN: optional('ANALYTICS_TOKEN', ''),

  // Managed-inference proxy upstream keys (Step 1). OPTIONAL at boot so the
  // service still runs without them — the /v1/* proxy routes return 503 until
  // they're set. These are OUR funded keys; they live ONLY here, never in the
  // desktop build. GEMINI_API_KEY also accepts the GOOGLE_AI_API_KEY alias.
  OPENROUTER_API_KEY: optional('OPENROUTER_API_KEY', ''),
  GEMINI_API_KEY: optional('GEMINI_API_KEY', '') || optional('GOOGLE_AI_API_KEY', ''),
  // Deepgram Nova-3 — PRIMARY transcribe upstream (harness 2026-07-07: 361-441ms
  // p50 with 147ms mins; verbatim params live in proxy.ts). OpenRouter whisper
  // stays as the fallback arm; either key alone keeps /v1/transcribe alive.
  DEEPGRAM_API_KEY: optional('DEEPGRAM_API_KEY', ''),

  // Scoped guard for POST /invites/register (the desktop app sends this when it
  // shares a beta invite). Optional — when unset, invite registration is
  // disabled (503) and the rest of the service runs unchanged. Rotate
  // independently of ADMIN_TOKEN; lower blast radius if it leaks from a build.
  INVITE_REGISTER_TOKEN: optional('INVITE_REGISTER_TOKEN', ''),

  // ── Founding Operator (one-time, tiered; 250-cohort) ────────────────────
  // License validity for a founder's minted token. Long-dated (≈10y) because
  // it's a lifetime grant; it's also re-minted on each account fetch, so this
  // is just the offline ceiling.
  FOUNDER_LICENSE_DAYS: Number.parseInt(optional('FOUNDER_LICENSE_DAYS', '3650'), 10),
  // HARD cohort ceiling (250 total). A checkout beyond this is recorded but NOT
  // granted founder status — we never silently exceed the cohort. The proxy
  // per-account fair-use cap (PROXY_CAP_FOUNDER_USD, read in proxy.ts) is what
  // keeps "managed inference included for life" solvent — there is no per-founder
  // credit block or locked rate (dropped per docs/founding-operator-tier.md).
  FOUNDER_CAP: Number.parseInt(optional('FOUNDER_CAP', '250'), 10),

  // Clerk issuer URL (e.g. https://<slug>.clerk.accounts.dev). Used to verify a
  // desktop's Clerk session token on /account/license, so a signed-in user can
  // pull THEIR OWN license — no shared secret shipped in the app. Optional:
  // when unset, /account/license is disabled (503).
  CLERK_ISSUER: optional('CLERK_ISSUER', ''),

  // Clerk Backend API secret key (sk_...). Used ONLY to resolve a Clerk user's
  // GitHub external account (users.getUser → externalAccounts) so an entitlement
  // can key on the STABLE GitHub identity, not just the exact Clerk user id
  // stamped in Stripe metadata (#1519). Powers: best-effort githubAccountId
  // backfill at checkout/account-fetch, the /account/license GitHub fallback +
  // clerkUserId migration, and the admin backfill endpoint. Optional: when unset
  // the server behaves exactly as before — no backfill, no fallback (the direct
  // clerkUserId lookup is unaffected). NEVER shipped in the desktop build.
  CLERK_SECRET_KEY: optional('CLERK_SECRET_KEY', ''),

  // Authorized parties for Clerk browser-session verification (audit #4).
  // Comma-separated origins that legitimately mint our browser sessions (e.g.
  // "https://o8.run"). A present `azp` must match one exactly, which blocks a
  // same-instance token minted by a sibling subdomain from being redeemed here
  // for a repo-write GitHub token. Native desktop tokens use Authorization with
  // no Origin and legitimately omit `azp`; issuer/signature/expiry verify them.
  // An empty list therefore rejects every browser-origin token while leaving the
  // native path available.
  CLERK_AUTHORIZED_PARTIES: optional('CLERK_AUTHORIZED_PARTIES', '')
    .split(',')
    .map((s) => s.trim())
    .filter(Boolean),

  // Managed GitHub App (the public "o8" App users install with one click).
  // This server holds the App's private key and mints short-lived installation
  // tokens for signed-in desktops (/github/app/token) — the key NEVER ships in
  // the app. All three optional: when unset the endpoint answers 503 and the
  // desktop falls back to device-flow OAuth exactly as before. The PEM follows
  // the same literal-\n normalization as LICENSE_PRIVATE_KEY.
  GITHUB_APP_ID: optional('GITHUB_APP_ID', ''),
  GITHUB_APP_PRIVATE_KEY: (() => {
    const raw = optional('GITHUB_APP_PRIVATE_KEY', '');
    return raw.includes('\\n') ? raw.replace(/\\n/g, '\n') : raw;
  })(),
  GITHUB_APP_SLUG: optional('GITHUB_APP_SLUG', ''),

  // Welcome email (best-effort, Resend). Optional: when RESEND_API_KEY is unset
  // the mail is skipped (Stripe sends its own receipt, and the license is
  // delivered by account-fetch on sign-in regardless).
  RESEND_API_KEY: optional('RESEND_API_KEY', ''),
  EMAIL_FROM: optional('EMAIL_FROM', 'o8 <founding@o8.run>'),

  // HTTP
  PORT: Number.parseInt(optional('PORT', '8080'), 10),
} as const;

export type Env = typeof env;
