import { useEffect, useLayoutEffect, useRef, useState } from 'react';

/**
 * Advance the reveal index, then extend to the next whitespace so whole WORDS
 * appear instead of splitting mid-word.
 *
 * Two goals in tension — FAST and SMOOTH — balanced by a proportional step with
 * a ceiling. Orchestrator replies usually arrive as one big buffered chunk (the
 * reply is already fully generated by the time the first byte hits the client),
 * so the reveal is largely cosmetic: it must make a done answer feel like fast
 * live streaming, not "the answer is ready but it's slowly typing it out." So
 * step = 20% of the remaining backlog (drains a big chunk quickly) capped at 32
 * chars/frame (~1900 chars/s at 60fps) — fast, but still a continuous stream,
 * never the front-loaded 185/145/115-char spike that read as "shooting in". The
 * proportional term also means a genuinely incremental backend stream is matched
 * gently (small backlog → small step), and it eases the last ~160 chars to a
 * soft stop. Time-to-first-token is unaffected: the very first frame already
 * reveals a step's worth, so text appears the instant the chunk lands. Pure +
 * synchronous so it's unit-testable without rAF.
 */
export function nextRevealIndex(current: number, text: string): number {
  const len = text.length;
  if (current >= len) return len;
  const remaining = len - current;
  const step = Math.min(32, Math.max(4, Math.ceil(remaining * 0.2)));
  let next = Math.min(len, current + step);
  // Extend to the next whitespace so whole words appear — but cap the search so
  // a giant unbroken token (URL, base64 blob) can't dump in a single frame.
  const cap = next + 10;
  while (next < len && next < cap && !/\s/.test(text[next]!)) next += 1;
  return next;
}

function prefersReducedMotion(): boolean {
  if (typeof window === 'undefined' || !window.matchMedia) return false;
  return window.matchMedia('(prefers-reduced-motion: reduce)').matches;
}

/**
 * Smoothly reveal streaming text instead of dumping each network burst.
 *
 * While `streaming`, the returned text catches up to `text` a few chars per
 * animation frame (snapped to word boundaries), giving a steady typewriter feel
 * no matter how bursty the deltas arrive — the orchestrator backend often sends
 * whole lines/paragraphs in one event, which used to pop in as jarring chunks.
 * When not streaming (history, or the turn finished) the full text shows
 * immediately, and reduced-motion users always get it instantly.
 *
 * The rAF loop self-stops when caught up and restarts on the next burst (no idle
 * churn between deltas), and reads the target via a ref so it never streams a
 * stale closure's text.
 */
export function useSmoothText(text: string, streaming: boolean): string {
  const reduced = prefersReducedMotion();
  // Once a message has streamed, keep pacing its leftover tail after
  // `streaming` flips false. A never-streamed history message shows in full.
  const [everStreamed, setEverStreamed] = useState(streaming);
  if (streaming && !everStreamed) setEverStreamed(true);
  const animate = (streaming || everStreamed) && !reduced;
  const [revealed, setRevealed] = useState(animate ? 0 : text.length);
  const visibleReveal = !animate ? text.length : revealed > text.length ? 0 : revealed;
  if (visibleReveal !== revealed) setRevealed(visibleReveal);
  const idxRef = useRef(animate ? 0 : text.length);
  const targetRef = useRef(text);
  const rafRef = useRef<number | null>(null);
  const runningRef = useRef(false);

  useLayoutEffect(() => {
    targetRef.current = text;
  }, [text]);

  // Not animating (history / reduced-motion) → show everything now.
  useEffect(() => {
    if (animate) return;
    if (rafRef.current != null) { cancelAnimationFrame(rafRef.current); rafRef.current = null; }
    runningRef.current = false;
    idxRef.current = targetRef.current.length;
    setRevealed(targetRef.current.length);
  }, [animate, text]);

  // Drive the reveal. Re-runs whenever `text` grows (a new burst) or `streaming`
  // ends (drain the tail); the loop self-stops when caught up and the next burst
  // restarts it. Reads target via ref → no stale closure.
  useEffect(() => {
    if (!animate) return;
    if (idxRef.current > targetRef.current.length) idxRef.current = 0; // hook reused by a new stream
    const tick = () => {
      const next = nextRevealIndex(idxRef.current, targetRef.current);
      idxRef.current = next;
      setRevealed(next);
      if (next < targetRef.current.length) {
        rafRef.current = requestAnimationFrame(tick);
      } else {
        runningRef.current = false;
        rafRef.current = null;
      }
    };
    if (!runningRef.current && idxRef.current < targetRef.current.length) {
      runningRef.current = true;
      rafRef.current = requestAnimationFrame(tick);
    }
  }, [animate, text, streaming]);

  useEffect(() => () => {
    if (rafRef.current != null) cancelAnimationFrame(rafRef.current);
    rafRef.current = null;
    runningRef.current = false;
  }, []);

  return animate ? text.slice(0, visibleReveal) : text;
}
