import type { FleetSnapshot } from '@/lib/fleet/types';

export const demoFleet: FleetSnapshot = {
  generatedAt: '2026-03-11T21:36:00Z',
  meta: {
    mode: 'demo',
    sourceLabel: 'Demo fleet snapshot',
    mirrorMode: 'demo-only',
    note: 'Live OpenClaw bridge not attached yet. Demo data is filling the shell.',
  },
  squads: [
    {
      id: 'squad-platform',
      name: 'Platform Core',
      status: 'healthy',
      throughputLabel: '3 runs moving',
      blockers: 0,
      alerts: 1,
      liveSessions: 3,
      members: ['agent-mister', 'agent-ace', 'agent-hawk'],
    },
    {
      id: 'squad-mobile',
      name: 'Mobile Remote',
      status: 'watching',
      throughputLabel: '1 audit, 1 spec',
      blockers: 0,
      alerts: 1,
      liveSessions: 2,
      members: ['agent-remodex-audit', 'agent-mobile-ui'],
    },
  ],
  agents: [
    {
      id: 'agent-mister',
      name: 'Assistant',
      squadId: 'squad-platform',
      runtime: 'openclaw',
      model: 'gpt-5.4',
      status: 'running',
      currentTask: 'Bootstrapping shell + fleet contract',
      workspace: 'repos/cortex-ide',
      branch: 'main',
      sessionKey: 'agent:main:main',
      approvalStatus: 'none',
      lastEventAt: '2m ago',
      context: { usedPercent: 41, trend: 'rising' },
      cost: { sessionUsd: 3.42, dailyUsd: 7.13 },
      alerts: 0,
      sessionKind: 'direct',
      surfaceLabel: 'Direct session',
      isCurrentSession: true,
      tokenUsage: { totalTokens: 144992, remainingTokens: 855008, fresh: true },
    },
    {
      id: 'agent-ace',
      name: 'Niot',
      squadId: 'squad-platform',
      runtime: 'openclaw',
      model: 'gpt-5.3-codex',
      status: 'reviewing',
      currentTask: 'Pattern audit for mobile bridge reuse',
      workspace: 'repos/cortex-ide',
      branch: 'research/remodex-audit',
      sessionKey: 'agent:ace:main',
      approvalStatus: 'pending',
      lastEventAt: '8m ago',
      context: { usedPercent: 26, trend: 'stable' },
      cost: { sessionUsd: 1.14, dailyUsd: 2.71 },
      alerts: 1,
      sessionKind: 'direct',
      surfaceLabel: 'Direct session',
      tokenUsage: { totalTokens: 78640, remainingTokens: 921360, fresh: true },
    },
    {
      id: 'agent-hawk',
      name: 'Hawk',
      squadId: 'squad-platform',
      runtime: 'openclaw',
      model: 'gpt-5.3-codex',
      status: 'idle',
      currentTask: 'Waiting for a reviewable surface',
      workspace: 'repos/cortex-ide',
      branch: 'main',
      sessionKey: 'agent:hawk:main',
      approvalStatus: 'none',
      lastEventAt: '14m ago',
      context: { usedPercent: 12, trend: 'falling' },
      cost: { sessionUsd: 0.42, dailyUsd: 1.03 },
      alerts: 0,
      sessionKind: 'direct',
      surfaceLabel: 'Direct session',
      tokenUsage: { totalTokens: 25961, remainingTokens: 974039, fresh: true },
    },
    {
      id: 'agent-remodex-audit',
      name: 'Remodex Audit',
      squadId: 'squad-mobile',
      runtime: 'custom',
      model: 'analysis-only',
      status: 'waiting',
      currentTask: 'Audit keep / borrow / replace matrix',
      workspace: 'external/remodex',
      branch: 'n/a',
      sessionKey: 'draft:mobile-audit',
      approvalStatus: 'none',
      lastEventAt: '5m ago',
      context: { usedPercent: 0, trend: 'stable' },
      cost: { sessionUsd: 0, dailyUsd: 0 },
      alerts: 0,
      sessionKind: 'draft',
      surfaceLabel: 'Research draft',
    },
    {
      id: 'agent-mobile-ui',
      name: 'Mobile Remote UI',
      squadId: 'squad-mobile',
      runtime: 'custom',
      model: 'prototype',
      status: 'blocked',
      currentTask: 'Waiting on pairing contract finalization',
      workspace: 'repos/cortex-ide/mobile',
      branch: 'mobile/inbox-v0',
      sessionKey: 'draft:mobile-ui',
      approvalStatus: 'pending',
      lastEventAt: '1m ago',
      context: { usedPercent: 0, trend: 'stable' },
      cost: { sessionUsd: 0, dailyUsd: 0 },
      alerts: 2,
      sessionKind: 'draft',
      surfaceLabel: 'Prototype lane',
    },
  ],
  events: [
    {
      id: 'evt-1',
      severity: 'info',
      agentId: 'agent-mister',
      squadId: 'squad-platform',
      title: 'Shell scaffold in progress',
      detail: 'Bootstrapping desktop command-center layout and live demo data.',
      timestamp: '2m ago',
    },
    {
      id: 'evt-2',
      severity: 'warning',
      agentId: 'agent-mobile-ui',
      squadId: 'squad-mobile',
      title: 'Pairing contract still draft',
      detail: 'Mobile route is waiting on a provider-agnostic bridge contract before wiring actions.',
      timestamp: '1m ago',
    },
    {
      id: 'evt-3',
      severity: 'success',
      agentId: 'agent-ace',
      squadId: 'squad-platform',
      title: 'Issue map translated into execution lanes',
      detail: 'Phase milestones and epics are now real GitHub issues in the private repo.',
      timestamp: '18m ago',
    },
  ],
  artifacts: [
    {
      kind: 'diff',
      title: 'Shell bootstrap diff',
      state: 'new',
      agentId: 'agent-mister',
      detail: 'Initial desktop shell surface changed files.',
    },
    {
      kind: 'doc',
      title: 'Fleet state model',
      state: 'reviewing',
      agentId: 'agent-ace',
      detail: 'Bounded contract for agent / squad / event status.',
    },
    {
      kind: 'doc',
      title: 'Runtime adapter contract',
      state: 'reviewing',
      agentId: 'agent-mister',
      detail: 'Explains truthful runtime control vs fake spawn behavior.',
    },
    {
      kind: 'screenshot',
      title: 'Desktop shell preview',
      state: 'new',
      agentId: 'agent-mobile-ui',
      detail: 'Latest desktop shell proof image from the command-center lane.',
    },
  ],
};
