export const COLLAPSED_BRANCH_RAIL_CAPSULE_WIDTH = 38;
export const COLLAPSED_BRANCH_RAIL_CAPSULE_RADIUS = 18;
export const COLLAPSED_BRANCH_RAIL_INSET = 8;
export const COLLAPSED_BRANCH_RAIL_WIDTH = COLLAPSED_BRANCH_RAIL_CAPSULE_WIDTH + (COLLAPSED_BRANCH_RAIL_INSET * 2);
export const WORKSPACE_RAIL_CORNER_RADIUS = COLLAPSED_BRANCH_RAIL_CAPSULE_RADIUS + COLLAPSED_BRANCH_RAIL_INSET;
export const WORKSPACE_RAIL_CORNER_SMOOTHING = 0.6;
