import type { OrchestratorSlashCommandDefinition } from './types';

export const ORCHESTRATOR_SLASH_COMMANDS: OrchestratorSlashCommandDefinition[] = [
  {
    command: '/orchestrate',
    name: 'orchestrate',
    title: 'Orchestrate',
    description: 'Claude coordinates; Codex codes; Claude verifies.',
    argHint: '<task>',
    requiresArgument: true,
    group: 'route',
    aliases: ['/fleet'],
  },
  {
    command: '/ask',
    name: 'ask',
    title: 'Ask the Brain',
    description: 'Query the Brain — directives, decisions, past outcomes.',
    argHint: '<question>',
    requiresArgument: true,
    group: 'context',
  },
  {
    command: '/compact',
    name: 'compact',
    title: 'Compact context',
    description: 'Run the compactor now and keep only the live tail verbatim.',
    group: 'thread',
  },
  {
    command: '/clear',
    name: 'clear',
    title: 'Clear thread',
    description: 'Archive the current thread and reset the orchestrator session.',
    group: 'thread',
  },
  {
    command: '/focus',
    name: 'focus',
    title: 'Focus scope',
    description: 'Keep only turns tied to one issue ref or file path.',
    argHint: '<packet>',
    requiresArgument: true,
    group: 'context',
  },
  {
    command: '/status',
    name: 'status',
    title: 'Thread status',
    description: 'Show tokens, cost, active dispatches, and recent decisions.',
    group: 'command',
  },
  {
    command: '/recall',
    name: 'recall',
    title: 'Recall archive',
    description: 'Pull relevant archived context back into the next turn.',
    argHint: '<keyword>',
    requiresArgument: true,
    group: 'context',
  },
  {
    command: '/handoff',
    name: 'handoff',
    title: 'Prep handoff',
    description: 'Prepare a compacted handoff prelude for a fresh session.',
    group: 'thread',
  },
  {
    command: '/rule',
    name: 'rule',
    title: 'Add a rule',
    description: 'Pin a session rule — inherited by every turn and dispatched agent.',
    argHint: '<rule text>',
    requiresArgument: true,
    group: 'context',
  },
  {
    command: '/rules',
    name: 'rules',
    title: 'Manage rules',
    description: 'Open the rules governing this session.',
    group: 'context',
  },
  {
    command: '/prompts',
    name: 'prompts',
    title: 'Saved prompts',
    description: 'Search the prompt library and insert one into this composer.',
    group: 'context',
  },
];
